name: PHPCS

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Check the coding standard
        run: composer phpcs
