name: PHPStan

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [develop, master]
        paths:
            - "**.php"
            - "phpstan.neon"
            - "phpstan-baseline.neon"
            - "composer.json"
            - "composer.lock"
            - "composer-dependencies.json"
            - "composer-dependencies.lock"

permissions:
    contents: read

concurrency:
    group: pr-phpstan-check-${{ github.ref }}
    cancel-in-progress: true

jobs:
    phpstan:
        name: PHPStan static analysis (PHP ${{ matrix.php }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ["7.4", "8.3", "8.5"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

            - name: Setup PHP
              uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
                  tools: composer:v2

            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-progress --optimize-autoloader

            - name: Run PHPStan
              run: composer phpstan
