name: Run PHPUnit Tests

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [develop, master]

permissions:
    contents: read

concurrency:
    group: pr-phpunit-check-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        name: PHPUnit Tests on PHP ${{ matrix.php-version }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php-version: ["7.4", "8.3", "8.5"]

        steps:
            - name: Checkout Code
              uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

            - name: Setup PHP
              uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, json
                  coverage: none

            - name: Install Dependencies
              run: composer install --no-interaction --no-progress

            - name: Run PHPUnit Tests
              run: composer test
